### ISSUE TITLE
not support mac arm?

### ISSUE THREAD

**Issue by wonb168** [polydbms/sheetreader-duckdb#56]
```

INSTALL sheetreader FROM community;
```
SQL 错误: HTTP Error: Failed to download extension "sheetreader" at URL "http://community-extensions.duckdb.org/v1.0.0/osx_arm64/sheetreader.duckdb_extension.gz"

Candidate extensions: "delta"

**Comment by wonb168** [comment]
v1.0.0， update to 1.1.3 OK

**Comment by freddie-freeloader** [comment]
Just for reference -- afaik, this extension was added to the community-extension with 1.1.0 -- so it might not be available for older versions
